import { Body, ConflictException, Controller, Delete, Get, NotFoundException, Param, Patch, Post, Req, UseGuards, ValidationPipe } from '@nestjs/common';
import { IsBoolean, IsIn, IsOptional, IsString, MinLength } from 'class-validator';
import * as bcrypt from 'bcrypt';
import { PrismaService } from '../prisma/prisma.service';
import { AdminGuard } from '../common/admin.guard';

class CityDto { @IsString() @MinLength(2) name!: string; }
class NeighborhoodDto { @IsString() @MinLength(2) name!: string; @IsString() cityId!: string; }
class BlockDto { @IsString() @MinLength(1) number!: string; @IsString() neighborhoodId!: string; @IsOptional() @IsString() description?: string; }
class UserDto { @IsString() @MinLength(2) name!: string; @IsString() @MinLength(3) username!: string; @IsOptional() @IsString() @MinLength(6) password?: string; @IsIn(['ADMIN','USER']) role!: 'ADMIN'|'USER'; @IsOptional() @IsBoolean() active?: boolean; }

@UseGuards(AdminGuard)
@Controller('admin')
export class AdminController {
  constructor(private prisma: PrismaService) {}
  private log(userId:string,action:string,description:string){return this.prisma.auditLog.create({data:{userId,action,description}});}
  @Get('cities') cities(){ return this.prisma.city.findMany({ orderBy:{name:'asc'}, include:{_count:{select:{neighborhoods:true}}} }); }
  @Post('cities') async createCity(@Body(new ValidationPipe({whitelist:true})) dto:CityDto,@Req() req:any){ try{const city=await this.prisma.city.create({data:dto});await this.log(req.user.sub,'CREATE_CITY',`Cidade criada: ${city.name}`);return city;}catch{throw new ConflictException('Já existe uma cidade com este nome.');} }
  @Patch('cities/:id') async updateCity(@Param('id') id:string,@Body(new ValidationPipe({whitelist:true})) dto:CityDto,@Req() req:any){const city=await this.prisma.city.update({where:{id},data:dto});await this.log(req.user.sub,'UPDATE_CITY',`Cidade alterada: ${city.name}`);return city;}
  @Delete('cities/:id') async deleteCity(@Param('id') id:string,@Req() req:any){await this.prisma.city.delete({where:{id}});await this.log(req.user.sub,'DELETE_CITY','Cidade excluída');return {success:true};}
  @Get('neighborhoods') neighborhoods(){return this.prisma.neighborhood.findMany({orderBy:{name:'asc'},include:{city:true,_count:{select:{blocks:true}}}});}
  @Post('neighborhoods') async createNeighborhood(@Body(new ValidationPipe({whitelist:true})) dto:NeighborhoodDto,@Req() req:any){try{const n=await this.prisma.neighborhood.create({data:dto});await this.log(req.user.sub,'CREATE_NEIGHBORHOOD',`Bairro criado: ${n.name}`);return n;}catch{throw new ConflictException('Este bairro já existe nesta cidade.');}}
  @Patch('neighborhoods/:id') async updateNeighborhood(@Param('id') id:string,@Body(new ValidationPipe({whitelist:true})) dto:NeighborhoodDto,@Req() req:any){const n=await this.prisma.neighborhood.update({where:{id},data:dto});await this.log(req.user.sub,'UPDATE_NEIGHBORHOOD',`Bairro alterado: ${n.name}`);return n;}
  @Delete('neighborhoods/:id') async deleteNeighborhood(@Param('id') id:string,@Req() req:any){await this.prisma.neighborhood.delete({where:{id}});await this.log(req.user.sub,'DELETE_NEIGHBORHOOD','Bairro excluído');return {success:true};}
  @Get('blocks') blocks(){return this.prisma.block.findMany({orderBy:{number:'asc'},include:{neighborhood:{include:{city:true}}}});}
  @Post('blocks') async createBlock(@Body(new ValidationPipe({whitelist:true})) dto:BlockDto,@Req() req:any){try{const b=await this.prisma.block.create({data:dto});await this.log(req.user.sub,'CREATE_BLOCK',`Quadra criada: ${b.number}`);return b;}catch{throw new ConflictException('Já existe uma quadra com este número nesse bairro.');}}
  @Patch('blocks/:id') async updateBlock(@Param('id') id:string,@Body(new ValidationPipe({whitelist:true})) dto:BlockDto,@Req() req:any){const b=await this.prisma.block.update({where:{id},data:dto});await this.log(req.user.sub,'UPDATE_BLOCK',`Quadra alterada: ${b.number}`);return b;}
  @Delete('blocks/:id') async deleteBlock(@Param('id') id:string,@Req() req:any){await this.prisma.block.delete({where:{id}});await this.log(req.user.sub,'DELETE_BLOCK','Quadra excluída');return {success:true};}
  @Get('users') users(){return this.prisma.user.findMany({select:{id:true,name:true,username:true,role:true,active:true,createdAt:true},orderBy:{name:'asc'}});}
  @Post('users') async createUser(@Body(new ValidationPipe({whitelist:true})) dto:UserDto,@Req() req:any){if(!dto.password) throw new ConflictException('Informe uma senha para o novo usuário.');try{const user=await this.prisma.user.create({data:{name:dto.name,username:dto.username,passwordHash:await bcrypt.hash(dto.password,12),role:dto.role,active:dto.active??true},select:{id:true,name:true,username:true,role:true,active:true}});await this.log(req.user.sub,'CREATE_USER',`Usuário criado: ${user.username}`);return user;}catch{throw new ConflictException('Este nome de usuário já está em uso.');}}
  @Patch('users/:id') async updateUser(@Param('id') id:string,@Body(new ValidationPipe({whitelist:true})) dto:UserDto,@Req() req:any){const data:any={name:dto.name,username:dto.username,role:dto.role,active:dto.active};if(dto.password)data.passwordHash=await bcrypt.hash(dto.password,12);const user=await this.prisma.user.update({where:{id},data,select:{id:true,name:true,username:true,role:true,active:true}});await this.log(req.user.sub,'UPDATE_USER',`Usuário alterado: ${user.username}`);return user;}
  @Delete('users/:id') async deleteUser(@Param('id') id:string,@Req() req:any){const user=await this.prisma.user.findUnique({where:{id}});if(!user)throw new NotFoundException('Usuário não encontrado.');await this.prisma.user.delete({where:{id}});await this.log(req.user.sub,'DELETE_USER',`Usuário excluído: ${user.username}`);return {success:true};}
  @Get('audit') audit(){return this.prisma.auditLog.findMany({take:100,orderBy:{createdAt:'desc'},include:{user:{select:{name:true,username:true}}}});}
  @Post('neighborhoods/:id/reset') async resetNeighborhood(@Param('id') id:string,@Req() req:any){const neighborhood=await this.prisma.neighborhood.findUnique({where:{id},include:{blocks:true,cycles:{orderBy:{number:'desc'},take:1}}});if(!neighborhood)throw new NotFoundException('Bairro não encontrado.');if(!neighborhood.blocks.length)throw new ConflictException('Este bairro não possui quadras.');if(neighborhood.blocks.some(b=>b.status!=='COMPLETED'))throw new ConflictException('O bairro só pode ser resetado quando todas as quadras estiverem concluídas.');const current=neighborhood.cycles[0];await this.prisma.$transaction(async tx=>{if(current)await tx.cycle.update({where:{id:current.id},data:{finishedAt:new Date()}});if(current)await tx.blockHistory.createMany({data:neighborhood.blocks.map(b=>({action:'RESET' as const,blockId:b.id,cycleId:current.id,userId:req.user.sub}))});await tx.block.updateMany({where:{neighborhoodId:id},data:{status:'PENDING',completedAt:null,completedById:null}});await tx.cycle.create({data:{neighborhoodId:id,number:(current?.number||0)+1}});await tx.auditLog.create({data:{userId:req.user.sub,action:'RESET_NEIGHBORHOOD',description:`Bairro resetado: ${neighborhood.name}`}});});return {success:true};}
}
